@extends('layouts.admin')
@section('title', 'Contributions')
@section('content')
<div class="page-head"><div><h1>Contributions</h1><p>Verify BHIM UPI references before payments appear publicly.</p></div><a class="btn secondary" href="{{ route('support-fund.index') }}" target="_blank" rel="noopener">Open public page</a></div>
<div class="grid stats"><div class="stat"><span>Pending verification</span><strong>{{ number_format($pendingCount) }}</strong></div><div class="stat"><span>Verified support</span><strong>₹{{ number_format((float) $verifiedTotal, 2) }}</strong></div></div>
@if(session('success'))<div class="alert success">{{ session('success') }}</div>@endif
<form class="filters" method="GET"><select class="input" name="status"><option value="">All statuses</option>@foreach(['pending'=>'Pending','verified'=>'Verified','rejected'=>'Rejected'] as $value=>$label)<option value="{{ $value }}" @selected($status===$value)>{{ $label }}</option>@endforeach</select><button class="btn" type="submit">Filter</button>@if($status)<a class="btn secondary" href="{{ route('admin.contributions.index') }}">Clear</a>@endif</form>
<section class="panel"><div class="table-wrap"><table><thead><tr><th>Contributor</th><th>Amount</th><th>UPI reference</th><th>Public display</th><th>Submitted</th><th>Review</th></tr></thead><tbody>
@forelse($contributions as $contribution)
<tr><td><strong>{{ $contribution->contributor_name }}</strong><br><span class="muted">{{ $contribution->email ?: 'No email' }}</span><br><span class="muted">{{ $contribution->phone ?: 'No phone' }}</span>@if($contribution->message)<br><span class="muted">{{ Str::limit($contribution->message, 55) }}</span>@endif</td><td><strong>₹{{ number_format((float) $contribution->amount, 2) }}</strong><br><span class="badge {{ $contribution->status === 'pending' ? 'new' : ($contribution->status === 'rejected' ? 'closed' : '') }}">{{ $contribution->status }}</span></td><td><code>{{ $contribution->transaction_reference }}</code></td><td>{{ $contribution->anonymous ? 'Anonymous' : ($contribution->show_publicly ? 'Name + amount' : 'Anonymous') }}</td><td>{{ $contribution->created_at->format('d M Y, h:i A') }}</td><td><form method="POST" action="{{ route('admin.contributions.update', $contribution) }}">@csrf @method('PATCH')<select class="input" name="status">@foreach(['pending'=>'Pending','verified'=>'Verified','rejected'=>'Rejected'] as $value=>$label)<option value="{{ $value }}" @selected($contribution->status===$value)>{{ $label }}</option>@endforeach</select><input class="input" name="admin_notes" maxlength="2000" value="{{ $contribution->admin_notes }}" placeholder="Private admin note"><button class="btn" type="submit">Save</button></form></td></tr>
@empty<tr><td class="empty" colspan="6">No matching contribution submissions.</td></tr>@endforelse
</tbody></table></div><div class="pagination">{{ $contributions->links() }}</div></section>
@endsection
