@extends('layouts.app')
@section('page_title','Create Support Ticket')
@section('page_subtitle','Tell us what went wrong and we will help you resolve it.')
@section('content')
<style>.support-form{max-width:800px}.support-grid{display:grid;grid-template-columns:1fr 1fr;gap:15px}.support-field{display:grid;gap:6px}.support-field.full{grid-column:1/-1}.support-field label{font-size:11px;font-weight:850;color:var(--muted)}.support-field input,.support-field select,.support-field textarea{width:100%}.support-field textarea{min-height:190px}.support-warning{margin-bottom:16px;padding:13px 15px;border:1px solid color-mix(in srgb,var(--warn) 28%,var(--line));border-radius:12px;color:var(--muted);background:color-mix(in srgb,var(--warn) 7%,transparent);font-size:11px}.support-warning strong{color:var(--warn)}.support-actions{display:flex;gap:10px;margin-top:17px}@media(max-width:650px){.support-grid{grid-template-columns:1fr}.support-field.full{grid-column:auto}}</style>
<div id="supportApp" data-page-title="Create Support Ticket" data-page-subtitle="Tell us what went wrong and we will help you resolve it.">
<section class="panel support-form"><div class="support-warning"><strong>Protect your account:</strong> Never include passwords, API secrets, private keys, recovery codes, or withdrawal credentials in a support message.</div><form method="POST" action="{{ route('support.store') }}">@csrf<div class="support-grid"><div class="support-field full"><label for="subject">Subject</label><input id="subject" name="subject" value="{{ old('subject') }}" maxlength="160" required placeholder="Briefly describe the problem">@error('subject')<span class="error">{{ $message }}</span>@enderror</div><div class="support-field"><label for="category">Category</label><select id="category" name="category" required>@foreach($categories as $value=>$label)<option value="{{ $value }}" @selected(old('category')===$value)>{{ $label }}</option>@endforeach</select></div><div class="support-field"><label for="priority">Priority</label><select id="priority" name="priority" required>@foreach(['low'=>'Low','normal'=>'Normal','high'=>'High','urgent'=>'Urgent — account unusable'] as $value=>$label)<option value="{{ $value }}" @selected(old('priority','normal')===$value)>{{ $label }}</option>@endforeach</select></div><div class="support-field full"><label for="message">What happened?</label><textarea id="message" name="message" maxlength="5000" required placeholder="Include the page, expected result, what happened, and any safe error message.">{{ old('message') }}</textarea>@error('message')<span class="error">{{ $message }}</span>@enderror</div></div><div class="support-actions"><button class="btn" type="submit">Create ticket</button><a class="btn secondary" href="{{ route('support.index') }}">Cancel</a></div></form></section>
</div>
@include('support._ajax')
@endsection
