@extends('layouts.app')
@section('page_title',$supportTicket->subject)
@section('page_subtitle',$supportTicket->ticket_number.' · '.str_replace('_',' ',$supportTicket->status))
@section('content')
<style>.ticket-layout{display:grid;grid-template-columns:minmax(0,1fr) 270px;gap:16px}.conversation{padding:18px}.messages{display:grid;gap:13px}.message{max-width:82%;padding:13px 15px;border:1px solid var(--line);border-radius:15px;background:rgba(255,255,255,.035)}.message.user{justify-self:end;border-bottom-right-radius:4px;background:color-mix(in srgb,var(--accent) 10%,var(--panel))}.message.admin{justify-self:start;border-bottom-left-radius:4px;background:color-mix(in srgb,var(--accent-2) 8%,var(--panel))}.message-head{display:flex;justify-content:space-between;gap:16px;margin-bottom:5px;color:var(--muted);font-size:9px;font-weight:800;text-transform:uppercase}.message-body{white-space:pre-wrap;word-break:break-word}.reply-box{margin-top:18px;padding-top:18px;border-top:1px solid var(--line)}.reply-box textarea{width:100%;min-height:120px}.ticket-details{padding:17px}.detail-row{padding:10px 0;border-bottom:1px solid var(--line)}.detail-row:last-child{border:0}.detail-row small,.detail-row strong{display:block}.detail-row small{color:var(--muted);font-size:9px;text-transform:uppercase}.detail-row strong{margin-top:3px;text-transform:capitalize}.security-note{margin-top:12px;color:var(--warn);font-size:10px}.ticket-actions{display:grid;gap:8px;margin-top:14px}@media(max-width:800px){.ticket-layout{grid-template-columns:1fr}.message{max-width:94%}}</style>
<div id="supportApp" data-page-title="{{ $supportTicket->subject }}" data-page-subtitle="{{ $supportTicket->ticket_number }} · {{ str_replace('_',' ',$supportTicket->status) }}">
<div class="ticket-layout"><section class="panel conversation"><div class="messages">@foreach($supportTicket->messages as $message)<article class="message {{ $message->sender_type }}"><div class="message-head"><span>{{ $message->sender_type==='admin'?'TradeYatra Support':'You' }}</span><time>{{ $message->created_at->format('d M Y, h:i A') }}</time></div><div class="message-body">{{ $message->body }}</div></article>@endforeach</div>@if($supportTicket->status!=='closed')<form class="reply-box" method="POST" action="{{ route('support.reply',$supportTicket) }}">@csrf<label for="message"><strong>Reply</strong></label><textarea id="message" name="message" maxlength="5000" required placeholder="Write your reply…">{{ old('message') }}</textarea>@error('message')<span class="error">{{ $message }}</span>@enderror<p class="security-note">Never send passwords, API secrets, private keys, or recovery codes.</p><button class="btn" type="submit">Send reply</button></form>@endif</section><aside class="panel ticket-details"><div class="detail-row"><small>Status</small><strong>{{ str_replace('_',' ',$supportTicket->status) }}</strong></div><div class="detail-row"><small>Priority</small><strong>{{ $supportTicket->priority }}</strong></div><div class="detail-row"><small>Category</small><strong>{{ str_replace('_',' ',$supportTicket->category) }}</strong></div><div class="detail-row"><small>Created</small><strong>{{ $supportTicket->created_at->format('d M Y') }}</strong></div><div class="detail-row"><small>Assigned to</small><strong>{{ $supportTicket->assignedAdmin?->name ?? 'Support team' }}</strong></div><div class="ticket-actions">@if(!in_array($supportTicket->status,['resolved','closed']))<form method="POST" action="{{ route('support.status',$supportTicket) }}">@csrf @method('PATCH')<input type="hidden" name="action" value="resolve"><button class="btn secondary" type="submit">Mark resolved</button></form>@elseif($supportTicket->status==='resolved')<form method="POST" action="{{ route('support.status',$supportTicket) }}">@csrf @method('PATCH')<input type="hidden" name="action" value="reopen"><button class="btn secondary" type="submit">Reopen ticket</button></form>@endif<a class="btn secondary" href="{{ route('support.index') }}">All tickets</a></div></aside></div>
</div>
@include('support._ajax')
@endsection
